<Project>

    <PropertyGroup>
        <LangVersion>latest</LangVersion>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
        <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
        <Authors>aritchie;ShinyLib</Authors>
        <Product>Shiny.Actors</Product>

        <PackageLicenseExpression>MIT</PackageLicenseExpression>
        <RepositoryUrl>https://github.com/shinyorg/actors</RepositoryUrl>
        <RepositoryType>git</RepositoryType>

        <PackageIcon>icon.png</PackageIcon>
        <PackageReadmeFile>readme.md</PackageReadmeFile>
        <PackageReleaseNotes>https://shinylib.net/actors/release-notes</PackageReleaseNotes>
        <PackageProjectUrl>https://shinylib.net/actors</PackageProjectUrl>
    </PropertyGroup>

    <PropertyGroup Condition="'$(Configuration)' == 'Release'">
        <IncludeSource>True</IncludeSource>
        <SymbolPackageFormat>snupkg</SymbolPackageFormat>
        <PublishRepositoryUrl>True</PublishRepositoryUrl>
        <EmbedUntrackedSources>True</EmbedUntrackedSources>
    </PropertyGroup>

    <ItemGroup>
        <None Include="$(MSBuildThisFileDirectory)nuget.png" Pack="true" PackagePath="icon.png" Visible="false" />
        <None Include="$(MSBuildThisFileDirectory)README.md" Pack="true" PackagePath="readme.md" Visible="false" />
    </ItemGroup>

    <!-- versions come from version.json + git height -->
    <ItemGroup>
        <PackageReference Include="Nerdbank.GitVersioning" Version="3.10.94">
            <PrivateAssets>all</PrivateAssets>
            <IncludeAssets>runtime; build; native; contentfiles; analyzers</IncludeAssets>
        </PackageReference>
    </ItemGroup>

</Project>
